require('arcane.ui.lualine')
require('arcane.ui.alpha')
require('arcane.ui.bufferline')
require('arcane.ui.cybu')
require('arcane.ui.dressing')
require('arcane.ui.indent')
require('arcane.ui.lir')
require('arcane.ui.notify')
require('arcane.ui.nvim-tree')
require('arcane.ui.scrollbar')
require('arcane.ui.trouble')
require('arcane.ui.whichkey')
-- require('arcane.ui.legendary')
require('arcane.ui.zen-mode')
