-- local secrets = require("secrets")

-- require("github-notifications").setup({
-- 	-- username = secrets.username,
-- 	-- token = secrets.token,
-- 	username = "AbbasSrour",
-- 	token = "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",
-- 	icon = "", -- Icon to be shown in statusline
-- 	hide_statusline_on_all_read = true,
-- 	hide_entry_on_read = false, -- Whether to hide the Telescope entry after reading (buggy)
-- 	debounce_duration = 60, -- Minimum time until next refresh
-- 	cache = false, -- Opt in/out of caching
-- 	sort_unread_first = true,
-- 	mappings = {
-- 		mark_read = "<CR>",
-- 		hide = "d", -- remove from Telescope picker, but don't mark as read
-- 		-- open_in_browser = 'o', (WIP)
-- 	},
-- 	prompt_mappings = {
-- 		mark_all_read = "<C-r>",
-- 	}, -- keymaps that apply on a Telescope prompt level (insert mode)
-- })
